### ISSUE TITLE
Push to a group of devices 

### ISSUE THREAD

**Issue by markrey** [nebula-orchestrator/api-manager#17]
## Expected/Wanted Behavior
I would like to try to push to only specific set of devices.
How it is possible?

I could not find it in APIs
https://nebula.readthedocs.io/en/latest/api/

**Comment by naorlivne** [comment]
Hi @markrey,

It's not clear to me what your asking, is it that you have 2 different apps you want to push to different devices (app_a goes to devices of type_a and app_b goes to devices of type_b)? if that's the case you need to start each of the device types with a different APP_NAME envvar and create an app for each of those types, for instance you create 2 apps named "app_a" & "app_b" and start each of the devices of type_a with APP_NAME=app_a and of type_b with APP_NAME=app_b then when you want to push a new image\envvar\etc you only need to update the matching app and only devices who has that app under the APP_NAME will get that update (which is passed using the [update](https://nebula.readthedocs.io/en/latest/api/#update-some-app-params-put-patch) API endpoint)

If what your asking is how to update only a subset of devices running app_a (or app_b) then this isn't possible as it will create a split which would effectively means you have 2 different versions of the same app running at the same time.
